---
- block:
  - name: Clone in ohmyzsh
    git:
      repo: "{{ zsh_ohmyzsh_repo }}"
      dest: ~/.oh-my-zsh

  - name: Activate ohmyzsh
    lineinfile:
      dest: ~/.zshrc
      line: "{{ item.line }}"
      regexp: "{{ item.regex }}"
    with_items:
      - line: "export ZSH=$HOME/.oh-my-zsh"
        regex: "^export ZSH="
      - line: "plugins=({{ zsh_ohmyzsh_plugins | join(' ') }})"
        regex: "^plugins="
      - line: "source $ZSH/oh-my-zsh.sh"
        regex: "^source .*/oh-my-zsh.sh$"

  become_user: "{{ ansible_user_id }}"
